name: Proyecto de Innovacion y Emprendimiento
services:
  psql-db:
    image: postgres:17
    container_name: postgres_pg
    restart: always
    environment:
      POSTGRES_USER: acha
      POSTGRES_PASSWORD: gBffb9TKw7QzBgWod73fA
      POSTGRES_DB: pg
    ports:
      - 5454:5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - pg
    profiles:
      - database
      - all
  backend:
    container_name: back_pg
    build:
      context: ./back
    env_file:
      - ./back/.env
    ports:
      - 5000:5000
    networks:
      - pg
    profiles:
      - all
  front:
    container_name: front_pg
    ports:
      - 8810:4321
    env_file:
      - ./front/.env
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - pg
    profiles:
      - all

networks:
  pg:
    external: true
