name: Proyecto de Innovacion y Emprendimiento
services:
  db:
    image: postgres:17
    container_name: postgres_pg
    restart: always
    environment:
      POSTGRES_USER: acha
      POSTGRES_PASSWORD: gBffb9TKw7QzBgWod73fA
      POSTGRES_DB: pg
    ports:
      - "5444:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - pg
  backend:
    container_name: back_pg
    build:
      context: ./back
    depends_on:
      - db
    env_file:
      - ./back/.env
    ports:
      - 5000:5000
    networks:
      - pg
  front:
    container_name: front_pg
    ports:
      - 8810:4321
    env_file:
      - ./front/.env.prod
    build:
      context: ./front
      dockerfile: Dockerfile
    networks:
      - pg

networks:
  pg:
    external: true
